### ISSUE TITLE
misleading comments?

### ISSUE THREAD

**Issue by pierluigi-failla** [acidjunk/hutoma-client#1]
I get a little bit confused by the fact that you said to do not use `BaseHutoma` or  `HutomaUserKey` but to use instead the `Hutoma` class, could you provide an example for that? As far as I can see no `Hutoma` class is in the codebase...
I saw multiple references in the comments to `reddit` in `BaseHutoma` I think are typos due to cut&paste...

**Comment by acidjunk** [comment]
I updated the README: it's a project that just started; far from releasable/useable yet.
Indeed it's based on reddit client.
